In [2]:
import pandas as pd
import numpy as np

In [3]:
rng = np.random.RandomState(42)

In [4]:
rng

In [5]:
ser = pd.Series(rng.randint(0,10,4))

In [6]:
ser

0    6
1    3
2    7
3    4
dtype: int64

In [9]:
df= pd.DataFrame(rng.randint(0,10,(3,4)) , columns=['A',"B","C","D"])

In [10]:
df

A  B  C  D
0  1  7  5  1
1  4  0  9  5
2  8  0  9  2

In [11]:
np.sin(df*np.pi / 4)

A         B         C         D
0  7.071068e-01 -0.707107 -0.707107  0.707107
1  1.224647e-16  0.000000  0.707107 -0.707107
2 -2.449294e-16  0.000000  0.707107  1.000000

In [12]:
A = rng.randint(10,size=(3,4))

In [13]:
A

array([[6, 3, 8, 2],
       [4, 2, 6, 4],
       [8, 6, 1, 3]])

In [14]:
A-A[0]

array([[ 0,  0,  0,  0],
       [-2, -1, -2,  2],
       [ 2,  3, -7,  1]])

In [15]:
A[1,2]

6

In [16]:
A[1,1]

2

In [17]:
A[1,3]

4

In [18]:
A[1,0]

4

In [19]:
B = pd.DataFrame(A, columns=list("QRST"))

In [20]:
B

Q  R  S  T
0  6  3  8  2
1  4  2  6  4
2  8  6  1  3

In [21]:
B - B.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -2 -1 -2  2
2  2  3 -7  1

In [26]:
B.subtract(B['R'],axis=0)

Q  R  S  T
0  3  0  5 -1
1  2  0  4  2
2  2  0 -5 -3

In [35]:
df = pd.DataFrame([[1,      np.nan, 2],
                             [2,      3,      5],
                   [np.nan, 4,      6]])

In [36]:
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

SyntaxError: invalid syntax (<ipython-input-37-227d7aaa58cd>, line 1)

In [39]:
df[df.notnull()]

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [40]:
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [41]:
df.dropna()

0    1  2
1  2.0  3.0  5

In [43]:
index = [('California', 2000), ('California', 2010),
                  ('New York', 2000), ('New York', 2010),
                  ('Texas', 2000), ('Texas', 2010)]
populations = [33871648, 37253956,
                        18976457, 19378102,
                        20851820, 25145561]

In [44]:
populations

[33871648, 37253956, 18976457, 19378102, 20851820, 25145561]

In [45]:
index

[('California', 2000),
 ('California', 2010),
 ('New York', 2000),
 ('New York', 2010),
 ('Texas', 2000),
 ('Texas', 2010)]

In [46]:
index = pd.MultiIndex.from_tuples(index)

In [48]:
index

MultiIndex(levels=[['California', 'New York', 'Texas'], [2000, 2010]],
           labels=[[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]])

In [67]:
pop = pd.Series(populations, index=index)

In [68]:
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [56]:
pop.iloc[2]

18976457

In [59]:
pop_df = pop.unstack()

In [60]:
pop_df

2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [61]:
pop_df.stack()

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [62]:
pop_df = pd.DataFrame({'total': pop,
                                 'under18': [9267089, 9284094,4687374, 4318033,
5906301, 6879014]})

In [63]:
pop_df

total  under18
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687374
           2010  19378102  4318033
Texas      2000  20851820  5906301
           2010  25145561  6879014

In [64]:
pop_df.stack()

California  2000  total      33871648
                  under18     9267089
            2010  total      37253956
                  under18     9284094
New York    2000  total      18976457
                  under18     4687374
            2010  total      19378102
                  under18     4318033
Texas       2000  total      20851820
                  under18     5906301
            2010  total      25145561
                  under18     6879014
dtype: int64

In [69]:
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [70]:
pop_df.unstack()

total            under18         
                2000      2010     2000     2010
California  33871648  37253956  9267089  9284094
New York    18976457  19378102  4687374  4318033
Texas       20851820  25145561  5906301  6879014

In [78]:
pop_df.stack()

California  2000  total      33871648
                  under18     9267089
            2010  total      37253956
                  under18     9284094
New York    2000  total      18976457
                  under18     4687374
            2010  total      19378102
                  under18     4318033
Texas       2000  total      20851820
                  under18     5906301
            2010  total      25145561
                  under18     6879014
dtype: int64

In [79]:
f_u18 = pop_df['under18']/pop_df['total']

In [80]:
f_u18

California  2000    0.273594
            2010    0.249211
New York    2000    0.247010
            2010    0.222831
Texas       2000    0.283251
            2010    0.273568
dtype: float64

In [81]:
f_u18.unstack()

2000      2010
California  0.273594  0.249211
New York    0.247010  0.222831
Texas       0.283251  0.273568

In [82]:
pop_df.index.names = ['state', 'year']

In [83]:
pop_df

total  under18
state      year                   
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687374
           2010  19378102  4318033
Texas      2000  20851820  5906301
           2010  25145561  6879014

In [84]:
index = pd.MultiIndex.from_product([[2013, 2014], [1, 2]],
                                   names=['year', 'visit'])
columns = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'], ['HR', 'Temp']],
                                     names=['subject', 'type'])


In [85]:
data = np.round(np.random.randn(4,6),1)

In [86]:
data

array([[ 0.1, -1.8, -1.2,  0.5,  2.2, -0.8],
       [-1.6,  0.2,  1.3,  0.6,  0.3, -0.5],
       [ 0.7, -0.2,  0. , -0. , -0.6, -1.2],
       [ 0.2,  0.1, -0.2, -0.7, -0.1, -0.4]])

In [87]:
data[:, ::2] *= 10

In [88]:
data

array([[  1. ,  -1.8, -12. ,   0.5,  22. ,  -0.8],
       [-16. ,   0.2,  13. ,   0.6,   3. ,  -0.5],
       [  7. ,  -0.2,   0. ,  -0. ,  -6. ,  -1.2],
       [  2. ,   0.1,  -2. ,  -0.7,  -1. ,  -0.4]])

In [89]:
data += 37

In [90]:
data

array([[ 38. ,  35.2,  25. ,  37.5,  59. ,  36.2],
       [ 21. ,  37.2,  50. ,  37.6,  40. ,  36.5],
       [ 44. ,  36.8,  37. ,  37. ,  31. ,  35.8],
       [ 39. ,  37.1,  35. ,  36.3,  36. ,  36.6]])

In [91]:
health_data = pd.DataFrame(data, index=index, columns=columns)

In [92]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      38.0  35.2  25.0  37.5  59.0  36.2
     2      21.0  37.2  50.0  37.6  40.0  36.5
2014 1      44.0  36.8  37.0  37.0  31.0  35.8
     2      39.0  37.1  35.0  36.3  36.0  36.6

In [93]:
health_data["Guido"]

type          HR  Temp
year visit            
2013 1      25.0  37.5
     2      50.0  37.6
2014 1      37.0  37.0
     2      35.0  36.3

In [96]:
health_data.T[2013]

visit            1     2
subject type            
Bob     HR    38.0  21.0
        Temp  35.2  37.2
Guido   HR    25.0  50.0
        Temp  37.5  37.6
Sue     HR    59.0  40.0
        Temp  36.2  36.5

In [97]:
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [98]:
pop.unstack(level=0)

state  California  New York     Texas
year                                 
2000     33871648  18976457  20851820
2010     37253956  19378102  25145561

In [99]:
pop.unstack(level=1)

year            2000      2010
state                         
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [100]:
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [101]:
pop.unstack()

year            2000      2010
state                         
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [102]:
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [103]:
pop_flat = pop.reset_index(name = "population")

In [104]:
pop_flat

state  year  population
0  California  2000    33871648
1  California  2010    37253956
2    New York  2000    18976457
3    New York  2010    19378102
4       Texas  2000    20851820
5       Texas  2010    25145561

In [105]:
pop_flat.set_index(['state','year'])

population
state      year            
California 2000    33871648
           2010    37253956
New York   2000    18976457
           2010    19378102
Texas      2000    20851820
           2010    25145561

In [106]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      38.0  35.2  25.0  37.5  59.0  36.2
     2      21.0  37.2  50.0  37.6  40.0  36.5
2014 1      44.0  36.8  37.0  37.0  31.0  35.8
     2      39.0  37.1  35.0  36.3  36.0  36.6

In [107]:
data_mean = health_data.mean(level="year")

In [108]:
data_mean

subject   Bob        Guido          Sue       
type       HR   Temp    HR   Temp    HR   Temp
year                                          
2013     29.5  36.20  37.5  37.55  49.5  36.35
2014     41.5  36.95  36.0  36.65  33.5  36.20

In [109]:
data_mean.mean(axis=1,level="type")

type         HR  Temp
year                 
2013  38.833333  36.7
2014  37.000000  36.6